version: 2.1
jobs:
   build:
      machine:
          image: ubuntu-2004:202111-01
      environment:
         DOCKER_BUILDKIT: 1
         COMPOSE_DOCKER_CLI_BUILD: 1
      steps:
         - checkout
         - run:
              name: docker build complete image
              command: build_type=package make build

         - run:
              name: docker build and --target test
              command: build_type=package make test

         - run:
              name: test docker-compose definition
              command: make test-compose

         - run:
              name: login to Dockerhub for release
              command: echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin

         - run:
              name: push image version to Dockerhub
              command: build_type=package make release

         - run:
              name: build and push tools image version to Dockerhub
              command: build_type=package make tools

         - run:
              name: sync Dockerhub README
              command: >-
                docker run --rm -v $(pwd)/README.md:/data/README.md
                -e DOCKERHUB_USR=$DOCKER_LOGIN
                -e DOCKERHUB_PWD=$DOCKER_PWD
                -e DOCKERHUB_ORG=0labs
                -e DOCKERHUB_REPO=openethereum gofunky/readmyhub:stable

         - when:
              condition:
                equal: [ master, << pipeline.git.branch >> ]
              steps:
                - run:
                     name: release master version as latest
                     command: make latest
